import { sqliteTable, text, integer, real } from "drizzle-orm/sqlite-core";

// Auth tables will be generated by Better Auth CLI
export * from "./auth-schema";

// Posts table
export const posts = sqliteTable("posts", {
  id: text("id").primaryKey(),
  title: text("title").notNull(),
  description: text("description"),
  imageUrl: text("image_url").notNull(),
  tier: text("tier").notNull().default("free"), // free | subscriber | ppv
  ppvPrice: real("ppv_price"), // price in dollars for PPV
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  likes: integer("likes").default(0),
  category: text("category").default("photo"), // photo | video | exclusive
});

// Post unlocks (PPV purchases)
export const postUnlocks = sqliteTable("post_unlocks", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  postId: text("post_id").notNull(),
  unlockedAt: integer("unlocked_at", { mode: "timestamp" }).notNull(),
  amountPaid: real("amount_paid").notNull(),
});

// Tips
export const tips = sqliteTable("tips", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  message: text("message"),
  amount: real("amount").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  status: text("status").default("pending"), // pending | completed
});
